CREATE TABLE Motorista (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    telefone VARCHAR(20),
    documento VARCHAR(20) NOT NULL UNIQUE,
    veiculo VARCHAR(50),
    rendimento_km_litro DECIMAL(5,2) CHECK (rendimento_km_litro > 0),
    consentimento_lgpd_em TIMESTAMP              -- RNF06: data/hora do consentimento do titular
);

CREATE TABLE Gerente (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    telefone VARCHAR(20),
    email VARCHAR(100),
    equipe_sob_responsabilidade VARCHAR(100)
);

CREATE TABLE Roteiro (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data DATE NOT NULL,
    motorista_id INT NOT NULL,
    distancia_total DECIMAL(8,2) DEFAULT 0,
    tempo_total_parado INT DEFAULT 0,          -- em minutos (RN03)
    custo_estimado DECIMAL(10,2) DEFAULT 0,    -- RN07
    CONSTRAINT fk_roteiro_motorista FOREIGN KEY (motorista_id) REFERENCES Motorista(id)
);

CREATE TABLE Ponto (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    roteiro_id INT NOT NULL,
    endereco VARCHAR(255) NOT NULL,
    latitude DECIMAL(10,8),
    longitude DECIMAL(11,8),
    data_hora_chegada TIMESTAMP,
    data_hora_saida TIMESTAMP,
    tempo_parado_calculado INT DEFAULT 0 CHECK (tempo_parado_calculado >= 0),  -- em minutos
    ordem_no_roteiro INT NOT NULL CHECK (ordem_no_roteiro >= 1),
    CONSTRAINT fk_ponto_roteiro FOREIGN KEY (roteiro_id) REFERENCES Roteiro(id) ON DELETE CASCADE,
    CONSTRAINT uq_ponto_ordem UNIQUE (roteiro_id, ordem_no_roteiro),
    CONSTRAINT ck_ponto_horario CHECK (data_hora_saida IS NULL OR data_hora_chegada IS NULL
                                       OR data_hora_saida >= data_hora_chegada),
    CONSTRAINT ck_ponto_partida CHECK (ordem_no_roteiro > 1 OR tempo_parado_calculado = 0)
);

CREATE TABLE Parametro (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    valor_combustivel DECIMAL(6,2),
    km_litro_veiculo DECIMAL(5,2),
    custo_por_km DECIMAL(6,2),
    jornada_padrao VARCHAR(50),
    regras_calculo_tempo_parado TEXT
);

CREATE TABLE Usuario (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login VARCHAR(30) NOT NULL UNIQUE,
    senha_hash VARCHAR(200) NOT NULL,
    perfil VARCHAR(10) NOT NULL CHECK (perfil IN ('MOTORISTA', 'GERENTE', 'ADMIN')),
    motorista_id INT UNIQUE,
    CONSTRAINT fk_usuario_motorista FOREIGN KEY (motorista_id) REFERENCES Motorista(id) ON DELETE CASCADE,
    CONSTRAINT ck_usuario_motorista CHECK ((perfil = 'MOTORISTA') = (motorista_id IS NOT NULL))
);

INSERT INTO Parametro (valor_combustivel, km_litro_veiculo, custo_por_km, jornada_padrao, regras_calculo_tempo_parado)
VALUES (6.29, 9.80, 1.53, '8', 'Tempo parado = saída - chegada; ponto de partida não conta.');

CREATE TABLE Auditoria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_hora TIMESTAMP NOT NULL DEFAULT now(),
    usuario VARCHAR(100) NOT NULL,
    tabela VARCHAR(50) NOT NULL,
    registro_id INT NOT NULL,
    operacao VARCHAR(10) NOT NULL CHECK (operacao IN ('INSERT', 'UPDATE', 'DELETE')),
    dados_anteriores JSONB,
    dados_novos JSONB
);
